### ISSUE TITLE
Error with ipython notebook

### ISSUE THREAD

**Issue by degninou** [jvns/pandas-cookbook#39]
$ git clone https://github.com/jvns/pandas-cookbook.git
Cloning into 'pandas-cookbook'...
remote: Counting objects: 410, done.
Rreceivingemote: Total 410 (delta objects:  83% (34 0), reused 3/410), 10.50 MiB
0 (delta 0), pack-reused 410
Receiving objects: 100% (410/410), 10.51 MiB | 14.00 KiB/s, done.
Resolving deltas: 100% (208/208), done.
Checking connectivity... done.

DEGNINOU@DYEHADJI ~ (master)
$ cd pandas-cookbook/cookbook

DEGNINOU@DYEHADJI ~/pandas-cookbook/cookbook (master)
$ ipython notebook
Traceback (most recent call last):
  File "c:\Anaconda3\Scripts\ipython-script.py", line 3, in <module>
    from IPython import start_ipython
  File "c:\Anaconda3\lib\site-packages\IPython\__init__.py", line 47, in <module
>
    from .core.application import Application
  File "c:\Anaconda3\lib\site-packages\IPython\core\application.py", line 22, in
 <module>
    from traitlets.config.application import Application, catch_config_error
  File "c:\Anaconda3\lib\site-packages\traitlets\config\__init__.py", line 6, in
 <module>
    from .application import *
  File "c:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 17
, in <module>
    from decorator import decorator
ImportError: No module named 'decorator'

**Comment by jvns** [comment]
try `pip install decorator`? This is an issue with your python installation though.
